#!/bin/sh

# fix gnome apps slow start due to failing services
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

exec dockd --daemon  & # ThinkPad automatic actions on dock/undock
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources & # Enable the usage of ~/Xresources for colors/settings
xcompmgr & # Xorg compositor for transparency
xcalib -screen 0 ~/.local/resources/x220/ips.icc & # Set the ICC profile for ThinkPad x220 IPS display
xset r rate 300 50 & # Speed up keyboard input
unclutter & # Remove the mouse when idle
