#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources & # Enable the usage of ~/Xresources for colors/settings
xcalib -screen 0 ~/.local/resources/x220/ips.icc & # Set the ICC profile for ThinkPad x220 IPS display
exec dockd --daemon  & # ThinkPad automatic actions on dock/undock
picom & # Xorg compositor for transparency
xwallpaper --zoom ~/.local/resources/bg.png & # Set the wallpaper
xset r rate 300 50 & # Speed up keyboard input
clock &
unclutter & # Remove the mouse when idle
